version: '2.1'

services:
  bigchaindb_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      AUTH0_DOMAIN: "registree.eu.auth0.com"
      API_IDENTIFIER: "https://registree.rocks/apis"
      ALGORITHMS: "['RS256']"
      UPORT_ISSUER: "2ow5YgWEjhL1MGjk1Ze1z5znfrNnW3EjWtC"
      UPORT_VALIDATION_URL: "http://178.62.244.76:8080/validateJWT"
    depends_on:
      - bigchaindb
    networks:
      - backbone
      - apiaggregator_interconnector

  mongodb:
    image: mongo:3.6
    command: mongod
    networks:
      - backbone

  bigchaindb:
    depends_on:
      - mongodb
      - tendermint
    image: bigchaindb/bigchaindb:2.0.0-beta8
    environment:
      BIGCHAINDB_DATABASE_BACKEND: localmongodb
      BIGCHAINDB_DATABASE_HOST: mongodb
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
      BIGCHAINDB_WSSERVER_ADVERTISED_HOST: bigchaindb
      BIGCHAINDB_TENDERMINT_HOST: tendermint
      BIGCHAINDB_TENDERMINT_PORT: 26657
    networks:
      - backbone

  tendermint:
    image: tendermint/tendermint:0.22.8
    entrypoint: ''
    command: sh -c "tendermint init && tendermint node --consensus.create_empty_blocks=false --proxy_app=tcp://bigchaindb:26658"
    networks:
      - backbone

networks: 
  backbone:
    driver: bridge
  apiaggregator_interconnector:
    external: true
